server:
  port: 8087
spring:
  datasource:
    username: root
    password: 54188
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ourchat
    # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 6000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: ourchat的接口文档
  try-host: http://localhost:${server.port}
