server:
  port: 8087
spring:
  datasource:
    username: root
    password: 54188
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 6000
  mybatis:
    type-aliases-package: com.ourchat.demo.login.pojo
    mapper-locations: com.ourchat.demo.login.mapper
    configuration:
      map-underscore-to-camel-case: true
